<?
$PERM["log"]["2"]="D";
$PERM["log"]["3"]="D";
$PERM["log"]["4"]="D";
$PERM["log"]["6"]="D";
$PERM["log"]["5"]="D";
$PERM["log"]["7"]="D";
$PERM["log"]["8"]="D";
$PERM["log"]["*"]="D";
$PERM["video"]["*"]="R";
$PERM["pub"]["5"]="T_8";
$PERM["upload"]["5"]="T_8";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["/"]["*"]="R";
?>