<?
$aMenuLinks = Array(
	Array(
		"Акции", 
		"/stocks/", 
		Array(), 
		Array("IMG"=>"/local/templates/czebra_daewoo/front/img/new-mobil-card/icon-sale.svg"), 
		"" 
	),
	Array(
		"Доставка", 
		"/delivery/", 
		Array(), 
		Array("IMG"=>"/local/templates/czebra_daewoo/front/img/new-mobil-card/icon-delivery.svg"), 
		"" 
	),
	Array(
		"Адреса магазинов", 
		"/addresses/", 
		Array(), 
		Array("IMG"=>"/local/templates/czebra_daewoo/front/img/new-mobil-card/icon-pin.svg"), 
		"" 
	),
	Array(
		"Оплата", 
		"/payment/", 
		Array(), 
		Array("IMG"=>"/local/templates/czebra_daewoo/front/img/new-mobil-card/icon-wallet.svg"), 
		"" 
	),
	Array(
		"Гарантия XXL", 
		"/xxl_warranty/", 
		Array(), 
		Array("IMG"=>"/local/templates/czebra_daewoo/front/img/new-mobil-card/icon-xxl.svg"), 
		"" 
	),
	Array(
		"Видеообзоры", 
		"/video_reviews/", 
		Array(), 
		Array("IMG"=>"/local/templates/czebra_daewoo/front/img/new-mobil-card/icon-video.svg"), 
		"" 
	)
);
?>